name: NodeJS with Vite CI/CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]

    steps:
    - uses: actions/checkout@v4

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}

    # This step creates the .env.local file with your secret
    - name: Create .env file
      run: |
        echo "VITE_GEMINI_API_KEY=${{ secrets.GEMINI_API_KEY }}" > .env.local

    - name: Install dependencies
      run: npm install

    - name: Build with Vite
      run: npm run build

    # Upload the build artifact to be used in the deploy job
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: dist-files
        path: dist

  deploy:
    # Requires the build job to succeed
    needs: build
    runs-on: ubuntu-latest
    # Only run this job when pushing to the main branch
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'

    steps:
    - name: Download artifact
      uses: actions/download-artifact@v4
      with:
        name: dist-files

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        # The build output folder, relative to the repository root
        publish_dir: .
