  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]

    steps:
    - uses: actions/checkout@v4

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}

    # Assumes you have a secret named GEMINI_API_KEY in your repo settings
    - name: Create .env file
      run: |
        echo "VITE_GEMINI_API_KEY=${{ secrets.GEMINI_API_KEY }}" > .env.local

    - name: Install dependencies
      run: npm install

    - name: Build with Vite
      run: npm run build

    # --- FIX IS HERE ---
    # This entire step uploads the artifact.
    # Note the indentation of 'if', 'uses', and 'with' are the same.
    - name: Upload artifact
      if: matrix.node-version == '20.x'
      uses: actions/upload-artifact@v4
      with:
        name: dist-files
        path: dist
