name: NodeJS with Vite CI/CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    # --- FIX IS HERE ---
    # This block grants the necessary permissions for the job.
    permissions:
      contents: write  # Allows the action to push to the gh-pages branch
      pages: write     # Allows the action to create a GitHub Pages deployment
      id-token: write  # Required for some advanced deployment scenarios

    steps:
    - uses: actions/checkout@v4

    - name: Use Node.js 20.x
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'

    - name: Create .env file
      run: |
        echo "VITE_GEMINI_API_KEY=${{ secrets.GEMINI_API_KEY }}" > .env.local

    - name: Install dependencies
      run: npm install

    - name: Build with Vite
      run: npm run build

    - name: Deploy to GitHub Pages
      if: github.event_name == 'push' && github.ref == 'refs/heads/main'
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./dist
