jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]

    steps:
    - uses: actions/checkout@v4

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}

    - name: Create .env file
      run: |
        echo "VITE_GEMINI_API_KEY=${{ secrets.GEMINI_API_KEY }}" > .env.local

    - name: Install dependencies
      run: npm install

    - name: Build with Vite
      run: npm run build

    # Upload the build artifact ONLY from the Node 20.x job
    - name: Upload artifact
      # This condition ensures the artifact is uploaded only once
      if: matrix.node-version == '20.x'
      uses: actions/upload-artifact@v4
      with:
        name: dist-files
        path: dist```

With this change:
*   All three jobs will still install dependencies and run the build to ensure your code works on all specified Node versions.
*   However, **only the job running on Node.js 20.x** will upload the `dist` folder as an artifact.
*   Your `deploy` job will then run, download that single artifact, and deploy it as intended, resolving the conflict error.
